version: '3'

services: 
  app:
    build:
      context: node
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    container_name: app
    entrypoint: 
      dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    tty: true
    expose:
      - "80"
    depends_on:
      - db


  nginx:
    build:
      context: nginx
    networks:
      - nodenet
    volumes:
      - ./nginx:/usr/src/nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:8080"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    expose:
      - "3306"
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet
  
networks:
  nodenet:
    driver: bridge
